const { Address } = require('@ton/core');
const client = require('./adapter').client;
const supabase = require('../supabase');
const logger = require('../logger');
const tipService = require('../core/services/tip');
const rewardService = require('../core/services/reward');

class ChainIndexer {
    constructor() {
        this.isRunning = false;
        this.POLL_INTERVAL_MS = 10000;
        // The contracts we need to watch for events
        this.WATCH_ADDRESSES = [
            process.env.TOON_REGISTRY_ADDRESS,
            process.env.TOON_VAULT_ADDRESS,
            process.env.TOON_TIP_ADDRESS
        ].filter(Boolean);
    }

    async start() {
        if (this.isRunning) return;
        this.isRunning = true;
        logger.info('ChainIndexer started', { addresses: this.WATCH_ADDRESSES });
        this.runLoop();
    }

    async runLoop() {
        while (this.isRunning) {
            try {
                for (const addr of this.WATCH_ADDRESSES) {
                    await this.syncAddress(addr);
                }
            } catch (e) {
                logger.error('ChainIndexer loop error', e);
            }
            await new Promise(r => setTimeout(r, this.POLL_INTERVAL_MS));
        }
    }

    /**
     * @param {string} addressStr 
     */
    async syncAddress(addressStr) {
        const address = Address.parse(addressStr);
        
        // 1. Get cursor (last processed LT) from DB
        const { data: cursorData } = await supabase
            .from('indexer_cursors')
            .select('last_lt')
            .eq('address', addressStr)
            .single();
        
        const lastLt = cursorData ? cursorData.last_lt : '0';

        // 2. Fetch transactions from TON
        // In a production indexer, we would handle pagination if many txs exist.
        const txs = await client.getTransactions(address, { limit: 20 });
        
        // 3. Process new transactions only (LT > lastLt)
        // TON returns transactions from newest to oldest. We want to process oldest to newest.
        const newTxs = txs
            .filter(tx => BigInt(tx.lt) > BigInt(lastLt))
            .reverse();

        if (newTxs.length === 0) return;

        logger.info(`ChainIndexer: Processing ${newTxs.length} new transactions for ${addressStr}`);

        for (const tx of newTxs) {
            await this.processTransaction(tx, addressStr);
        }

        // 4. Update cursor
        const latestLt = newTxs[newTxs.length - 1].lt.toString();
        await supabase
            .from('indexer_cursors')
            .upsert({ address: addressStr, last_lt: latestLt }, { onConflict: 'address' });
    }

    /**
     * @param {any} tx 
     * @param {string} contractAddress 
     */
    async processTransaction(tx, contractAddress) {
        const txHash = tx.hash().toString('hex');
        
        // TON Tact contracts emit events as messages. 
        // We look at outMessages to find event bodies.
        for (const outMsg of tx.outMessages.values()) {
            if (outMsg.info.type !== 'external-out') continue;
            
            try {
                await this.handleEventMessage(outMsg.body, txHash, tx.lt.toString(), tx.now);
            } catch (e) {
                logger.error('Failed to parse event message', { txHash, error: e.message });
            }
        }
        
        // Also look at inMessage for direct triggers (like TipSent being the body)
        if (tx.inMessage && tx.inMessage.info.type === 'internal') {
             // In some cases, we might want to parse the in-message body if it contains an event
             // But usually, events are the out-messages (external-out).
        }
    }

    /**
     * @param {import('@ton/core').Slice} body 
     */
    async handleEventMessage(body, txHash, lt, timestamp) {
        const slice = body.beginParse();
        if (slice.remainingBits < 32) return;
        
        const op = slice.loadUint(32);
        
        // Map op-codes to event handlers
        // These op-codes are generated by Tact. 
        // We'll use a simplified mapping or look them up from the ABI.
        
        logger.info(`ChainIndexer: Detected event with op ${op.toString(16)} in tx ${txHash}`);
        
        // EXAMPLE: TipSent logic (we'd need the exact op code from the built ABI)
        // If we find a match, we link it to an intent.
        
        // Note: For this architectural pass, we're building the HOOKS. 
        // The exact OP mapping requires the compiled .abi files.
    }
}

module.exports = new ChainIndexer();
